export const FETCH = 'FETCH_ALL'
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'
export const FETCH_BY_ID = 'FETCH_BY_ID'
export const CREATE = 'CREATE_POST'
export const UPDATE = 'UPDATE_POST'
export const DELETE = 'DELETE_POST'
export const COMMENT = 'COMMENT'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const START_LOADING_POST = 'START_LOADING_POST'
export const STOP_LOADING_POST = 'STOP_LOADING_POST'

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const REDIRECT_TO_HOME = 'REDIRECT_TO_HOME'